environment: 'sandbox'
merchant_id: 'x8bphk2xcm3nwfjn'
public_key: 'qsgf4f5rhqknwmtn'
private_key: '30d29d800d1d19c36267c4294fc50a2e'
client_side_encryption_key: "MIIBCgKCAQEAwQFceH215IYP8hEWIzIG3Y1p0hBwGctolClpvKokePfvFf3Ovk4o/Y4jJK6pg1ClqqavzsxiGdnDNgI5e4ne1Q7LDh3mgtU59O+OaCu319vJqpmbKY1KwosM6SUCBVasXrsMSb8GJqRmI9nEKnO5VyikhiuVcWiQJ7dqL+xZgA0B90i/mTvMdeTVlAycvTPk8ZjTp4fSquYgg7jDEoLFCPJl2j5ATRAa402RtT/e1aEezSkAuTH9lSBvmonNIGeF11lZKN1sffD0oyESZYsJFfQID4Nz+WtY4s5YLgrjKoeSYV1abBvqM/9pGao7xsfj8SVApHvgQywSIvVxZm+NCQIDAQAB"