common: &common
  adapter: postgresql
  username: thaitanic
  password: thaitanic123
  host: localhost

development:
  <<: *common
  database: thaitanic_development

test: &test
  <<: *common
  database: thaitanic_test

staging:
  <<: *common
  database: thaitanic_production

production:
  <<: *common
  database: thaitanic_production
